model:
  channels: 32
  num_blocks: 7
  semantic_classes: 3
  instance_classes: 3
  sem2ins_classes: []
  semantic_only: True
  ignore_label: -100
  grouping_cfg:
    score_thr: 0.2
    radius: 0.3
    mean_active: 10
    class_numpoint_mean: [1600., 1200., 2100.]
    npoint_thr: 0.03  # absolute if class_numpoint == -1, relative if class_numpoint != -1
    ignore_classes: []
  instance_voxel_cfg:
    scale: 10
    spatial_shape: 20
  train_cfg:
    max_proposal_num: 200
    pos_iou_thr: 0.5
  test_cfg:
    x4_split: False
    cls_score_thr: 0.001
    mask_score_thr: -0.5
    min_npoint: 100
    eval_tasks: ['semantic']
  fixed_modules: []

data:
  train:
    type: 's3dis'
    data_root: 'dataset/s3dis/preprocess'
    prefix: ['Area_1', 'Area_2', 'Area_3', 'Area_4', 'Area_6']
    suffix: '_inst_nostuff.pth'
    repeat: 4
    training: True
    voxel_cfg:
      scale: 10
      spatial_shape: [128, 512]
      max_npoint: 50000
      min_npoint: 2500
  test:
    type: 's3dis'
    data_root: 'dataset/s3dis/preprocess'
    prefix: 'Area_5'
    suffix: '_inst_nostuff.pth'
    training: False
    voxel_cfg:
      scale: 10
      spatial_shape: [128, 512]
      max_npoint: 50000
      min_npoint: 2500

dataloader:
  train:
    batch_size: 2
    num_workers: 4
  test:
    batch_size: 1
    num_workers: 1

optimizer:
  type: 'Adam'
  lr: 0.001

fp16: True
epochs: 1000
step_epoch: 0
save_freq: 1
pretrain: './checkpoints/hais_ckpt_spconv2.pth'
work_dir: 'softgroup_transformer'
